fixed newline issue, add environment variable for root file

diff --git a/emd b/emd
--- a/emd
+++ b/emd
@@ -1,19 +1,23 @@
 #!/bin/bash
 
-if [ "$#" -eq 0 ]; then
-    echo "Missing Filename"
-    exit 1
+if [ -z "${EMD_ROOT_FILE}" ]; then
+    if [ "$#" -eq 0 ]; then
+        echo "Missing Filename"
+        exit 1
+    fi
+
+    filename=$1
+    shift
+else
+    filename="${EMD_ROOT_FILE}"
 fi
 
-filename=$1
-shift
-
-res=$(pandoc -f markdown -t json "${filename}" | python3 emd.py $@)
+cmd="pandoc -f markdown -t json ${filename} | python3 emd.py $@"
 
 # Check if there are no command-line arguments or the first argument is not "run"
 if [ "$#" -eq 0 ] || [ "$1" != "irun" ]; then
-    echo -n "${res}"
+    eval "$cmd"
 else
     # if this is a "run" command, then evaluate the command being returned
-    eval "${res}"
+    eval "$(eval "$cmd")"
 fi
